package gameet.entity;

public enum Caracteristicas {

	CREATIVO, INTUITIVO, METODICO, COLABORATIVO, INDEPENDIENTE, COMUNICATIVO, ANALITICO, AVENTURERO, AUDAZ,
	DISFRUTA_DE_LA_NARRATIVA, FAN_DE_LOS_ESPORTS, GEEK, RELAJADO, COMPETITIVO, EXPLORADOR, CONCENTRADO, APRENDIZ_RAPIDO,
	DEDICADO, ENTUSIASTA_DE_LA_REALIDAD_VIRTUAL, AMANTE_DE_LOS_JUEGOS_INDIE, COLECCIONISTA, FIEL_A_UNA_PLATAFORMA,
	GUSTO_POR_LOS_JUEGOS_RETRO, DESENFRENADO, ESTRATEGICO, JUGADOR_CASUAL, FAN_DE_LOS_MODS, TEAM_PLAYER, VISIONARIO,
	INTENSO, TECNÓFILO, ADAPTATIVO, PERSEVERANTE, CREATIVO_EN_EQUIPO, SOCIABLE, CAUTO, IMAGINATIVO, COMPETITIVO_JOCOSO,
	ESTILO_PROPIO, ORGANIZADO, APASIONADO_POR_LOS_GRÁFICOS, CAZADOR_DE_LOGROS, PERFECCIONISTA, CAPAZ_DE_MULTIATAREA,
	DIPLOMÁTICO_EN_LÍNEA, RECEPTIVO_AL_FEEDBACK, ENFOCADO_EN_LA_HISTORIA, JUGADOR_EVENTUAL, ESTRATEGA_TÁCTICO,
	CONSTRUCTIVO_EN_MUNDOS_ABIERTOS, AMANTE_DE_LA_MÚSICA_INGAME

}
