package gameet.entity;

public enum Caracteristicas {

	CREATIVO, INTUITIVO, METODICO, GEEK, RELAJADO, COLABORATIVO, INDEPENDIENTE, COMUNICATIVO, EXPLORADOR,
	COMPETITIVO, ANALITICO, AVENTURERO, AUDAZ, ESTRATEGICO, PERFECCIONISTA

}
