package gameet.entity;

public enum Consolas {

    XBOX_ONE, PLAYSTATION_4, NINTENDO_SWITCH, XBOX_360, PLAYSTATION_3, PLAYSTATION_5, XBOX_SERIES_X, PC, NINTENDO_WII_U,
    NINTENDO_DS, NINTENDO_3DS,XBOX_SERIES_S, PLAYSTATION_VITA, PLAYSTATION_PORTABLE_PSP
}
