package gameet.entity;

public enum Genero {

	ACCION, AVENTURA, ROL_RPG, ESTRATEGIA, DISPAROS_SHOOTER, PLATAFORMA, CARRERAS, DEPORTES, SIMULACION, SUPERVIVENCIA,
	TERROR_SURVIVAL_HORROR, ROMPECABEZAS_PUZZLE, MUNDO_ABIERTO, SANDBOX, INDIE, SIGILO, MULTIJUGADOR_EN_LINEA_MASIVO_MMO,
	BATTLE_ROYALE, ESTRATEGIS_EN_TIEMPO_REAL_RTS, LUCHA

}
